In [1]:
from __future__ import print_function
import torch

x = torch.Tensor(5,3)
print(x)




 0.0000e+00  0.0000e+00  4.1939e+36
 4.5769e-41  4.1931e+36  4.5769e-41
-6.8133e+10  3.0744e-41 -6.8133e+10
 3.0744e-41  8.9683e-44  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00
[torch.FloatTensor of size 5x3]



In [2]:
x = torch.rand(5,3)
print(x)



 0.8458  0.7831  0.8028
 0.4450  0.9836  0.1768
 0.0882  0.9593  0.0865
 0.6948  0.4323  0.4178
 0.1297  0.5110  0.2036
[torch.FloatTensor of size 5x3]



In [3]:
print(x.size())

torch.Size([5, 3])


In [4]:
y = torch.rand(5,3)
print(x+y)



 1.7708  1.5364  1.4270
 1.0898  1.1374  0.9300
 0.4590  1.7537  0.3433
 1.2436  1.2083  1.0593
 0.3219  1.3227  0.6666
[torch.FloatTensor of size 5x3]



In [5]:
result = torch.Tensor(5,3)
torch.add(x, y, out=result)
print(result)



 1.7708  1.5364  1.4270
 1.0898  1.1374  0.9300
 0.4590  1.7537  0.3433
 1.2436  1.2083  1.0593
 0.3219  1.3227  0.6666
[torch.FloatTensor of size 5x3]



In [6]:
y.add_(x)
print(y)
y.add(x)
print(y)


 1.7708  1.5364  1.4270
 1.0898  1.1374  0.9300
 0.4590  1.7537  0.3433
 1.2436  1.2083  1.0593
 0.3219  1.3227  0.6666
[torch.FloatTensor of size 5x3]


 1.7708  1.5364  1.4270
 1.0898  1.1374  0.9300
 0.4590  1.7537  0.3433
 1.2436  1.2083  1.0593
 0.3219  1.3227  0.6666
[torch.FloatTensor of size 5x3]



In [7]:
print(y[1,:])


 1.0898
 1.1374
 0.9300
[torch.FloatTensor of size 3]



In [8]:
x = torch.randn(4,4)
y = x.view(16)

torch.is_tensor(x)
print(torch.is_storage(x))

False


In [9]:
torch.numel(x)


16

In [10]:
torch.eye(4, out=x)
print(x)


 1  0  0  0
 0  1  0  0
 0  0  1  0
 0  0  0  1
[torch.FloatTensor of size 4x4]



In [11]:
import numpy as np
a = np.array([1, 2, 3])
t = torch.from_numpy(a)
t


 1
 2
 3
[torch.LongTensor of size 3]

In [12]:
np.append(a, [5])
print(a)
t = torch.from_numpy(a)
print(t)

[1 2 3]

 1
 2
 3
[torch.LongTensor of size 3]



In [14]:
x = torch.ones(5)
print(x)
y = x.numpy()
print(y)
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)
np.add(a, 1, out=a)
print(a)
print(b)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]

[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]

 1
 1
 1
 1
 1
[torch.DoubleTensor of size 5]

[2. 2. 2. 2. 2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



In [16]:
if torch.cuda.is_available():
    print("cuda is available.")
    x = x.cuda()
    y = y.cuda()
    print(x+y)
    